using System.Collections.Generic;
using System.Collections;
using UnityEngine;

public class DialogueTrigger : MonoBehaviour
{
    [Header("References")]
    public SubtitleController subtitleController;
    public DialogueData dialogue;
    public FirstPlayer player;

    private bool triggered = false;

    private void OnTriggerEnter(Collider other)
    {
        if (triggered) return;
        if (!other.CompareTag("Player")) return;

        triggered = true;

        // ðŸ”’ Bloquear SOLO movimiento (la cÃ¡mara sigue)
        if (player != null)
            player.canMove = false;

        subtitleController.PlayDialogue(dialogue);

        // â³ Esperar a que termine el diÃ¡logo
        StartCoroutine(WaitForDialogueEnd());
    }

    IEnumerator WaitForDialogueEnd()
    {
        // Espera hasta que el diÃ¡logo termine
        yield return new WaitUntil(() => !subtitleController.IsDialogueActive);

        // ðŸ”“ Habilitar movimiento
        if (player != null)
            player.canMove = true;
    }
}
